import "@styles/globals.css";
import { michroma, dancing } from "../fonts/font";
import type { Metadata } from "next";
import Header from "../components/header";
import Footer from "../components/footer";
import AuthProvider from "context/AuthProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${michroma.variable} ${dancing.variable}`}>
        <AuthProvider>
          <div className="flex flex-col overflow-x-auto ">
            <Header />
            {children}
            <Footer />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
