import "@styles/globals.css";
import { michroma, dancing } from "../fonts/font";
import type { Metadata } from "next";
import Header from "../components/Layout/header";
import Footer from "../components/Layout/footer";
import AuthProvider from "context/AuthProvider";
import { RecoilRootWrapper } from "./recoilContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${michroma.variable} ${dancing.variable}`}>
        <RecoilRootWrapper>
          <AuthProvider>
            <div className="flex flex-col min-h-screen mt-28">
              <Header />
              <div className="flex-grow">{children}</div>
              <Footer />
            </div>
          </AuthProvider>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
